# Generated by Django 4.1 on 2022-09-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата создания статьи')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='project-images', verbose_name='Изображение')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='project-banner', verbose_name='Банер')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='ArticlesArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата создания статьи')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='project-images', verbose_name='Изображение')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='project-banner', verbose_name='Банер')),
            ],
            options={
                'verbose_name': 'Архивная Статья',
                'verbose_name_plural': 'Архивные Статьи',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата жизни')),
                ('image', models.ImageField(upload_to='gallery-images', verbose_name='Фото автора')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название новости')),
                ('date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата создания новости')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='project-images', verbose_name='Изображение на показ')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='project-banner', verbose_name='Банер')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partner-image', verbose_name='Логотип партнера')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на сайт партнера')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200, verbose_name='Название партнера')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners_images', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=200, verbose_name='Инстаграм')),
                ('telegram', models.CharField(max_length=200, verbose_name='Телеграм')),
                ('facebook', models.CharField(max_length=200, verbose_name='Фейсбук')),
            ],
            options={
                'verbose_name': 'Социальная_сеть',
                'verbose_name_plural': 'Социальные_сети',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название статистики')),
                ('statistic', models.CharField(max_length=100, verbose_name='Статистика')),
            ],
            options={
                'verbose_name': 'Главная - Статистика',
                'verbose_name_plural': 'Главная - Статистика',
            },
        ),
    ]
