# Generated by Django 4.1 on 2022-09-06 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='articlesarchive',
            name='category_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Категории', to='main.categories'),
            preserve_default=False,
        ),
    ]
