# Generated by Django 4.1 on 2022-09-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categories_articlesarchive_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='articlesarchive',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='articlesarchive',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='banner',
        ),
        migrations.AddField(
            model_name='articles',
            name='category_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Категории', to='main.categories'),
            preserve_default=False,
        ),
    ]
