# Generated by Django 4.1 on 2022-09-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categoriesforarchieved_articlesarchive_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='comments',
            field=models.CharField(default=1, max_length=100, verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
