# Generated by Django 4.1 on 2022-09-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_statistic_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesforarchieved',
            options={'verbose_name': 'Категория для архивной статьи', 'verbose_name_plural': 'Категории для архивных статей'},
        ),
        migrations.AddField(
            model_name='statistic',
            name='lower',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Нижняя цифра'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='statistic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статистика'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название статистики'),
        ),
    ]
