# Generated by Django 4.1 on 2022-09-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_categoriesforarchieved_options_statistic_lower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название категории')),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='title',
            field=models.CharField(default=11, max_length=200, verbose_name='Название партнёра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.partnercategory', verbose_name='Категория партнера'),
            preserve_default=False,
        ),
    ]
