# Generated by Django 4.1 on 2022-09-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_partnercategory_partner_title_partner_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnercategory',
            options={'verbose_name': 'Кетегория партнёра', 'verbose_name_plural': 'Категории партнёров'},
        ),
        migrations.AddField(
            model_name='statistic',
            name='comments_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='comments_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='comments_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название статистики'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='title_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название статистики'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название статистики'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_partners', to='main.partnercategory', verbose_name='Категория партнера'),
        ),
    ]
