# Generated by Django 4.1 on 2022-09-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_partnercategory_options_statistic_comments_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название статьи'),
        ),
    ]
