# Generated by Django 4.1 on 2022-09-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_articles_text_en_articles_text_ky_articles_text_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Оглавление')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Оглавление')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Оглавление')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Оглавление')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст')),
                ('text_ky', models.TextField(null=True, verbose_name='Текст')),
                ('text_en', models.TextField(null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Для авторов',
            },
        ),
        migrations.AddField(
            model_name='articlesarchive',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articlesarchive',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articlesarchive',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articlesarchive',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='articlesarchive',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='articlesarchive',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название новости'),
        ),
    ]
