# Generated by Django 4.1 on 2022-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_imagescontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название партнёра'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название партнёра'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название партнёра'),
        ),
        migrations.AddField(
            model_name='partnercategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='partnercategory',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='partnercategory',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
    ]
