# Generated by Django 4.1 on 2022-09-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_partner_title_en_partner_title_ky_partner_title_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главный слоган')),
            ],
            options={
                'verbose_name': 'Галерея Слоган',
            },
        ),
    ]
