# Generated by Django 4.1 on 2022-09-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_maintagline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintagline',
            options={'verbose_name': 'Галерея Слоган', 'verbose_name_plural': 'Галерея Слоган'},
        ),
    ]
