# Generated by Django 4.1 on 2022-09-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_maintagline_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Первый слоган')),
            ],
            options={
                'verbose_name': 'Первый слоган',
                'verbose_name_plural': 'Первый слоган',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='pdf',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='word',
            field=models.FileField(default=111, upload_to=''),
            preserve_default=False,
        ),
    ]
