# Generated by Django 4.1.1 on 2022-09-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_videocontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Логотип')),
            ],
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='telegram',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='whatsapp',
            field=models.CharField(default=1, max_length=200, verbose_name='Ватсап'),
            preserve_default=False,
        ),
    ]
