# Generated by Django 4.1.1 on 2022-09-13 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_homepage_alter_socialmedia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Авторам - Категория',
                'verbose_name_plural': 'Авторам - Категория',
            },
        ),
        migrations.AddField(
            model_name='authors',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.authorcategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
