# Generated by Django 4.1.1 on 2022-09-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_authorcategory_authors_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Для авторов', 'verbose_name_plural': 'Для авторов'},
        ),
        migrations.RemoveField(
            model_name='authors',
            name='category',
        ),
        migrations.DeleteModel(
            name='AuthorCategory',
        ),
    ]
