# Generated by Django 4.1.1 on 2022-09-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_authors_options_remove_authors_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='Logo',
        ),
        migrations.AlterModelOptions(
            name='imagescontent',
            options={'verbose_name': 'Галерея Контент'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Логотип', 'verbose_name_plural': 'Логотип'},
        ),
    ]
