# Generated by Django 4.1.1 on 2022-09-13 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_authorcategory_authors_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Авторам', 'verbose_name_plural': 'Авторам'},
        ),
        migrations.AlterField(
            model_name='authors',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_category', to='main.authorcategory', verbose_name='Категория'),
        ),
    ]
