# Generated by Django 4.1.1 on 2022-09-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_authors_options_alter_authors_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название картинки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content')),
            ],
            options={
                'verbose_name': 'Картинки',
                'verbose_name_plural': 'Картинки',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='VideoContent',
        ),
    ]
