# Generated by Django 4.1.1 on 2022-09-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_content_delete_videocontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Эквалайзер')),
            ],
            options={
                'verbose_name': 'Эквалайзер',
                'verbose_name_plural': 'Эквалайзер',
            },
        ),
    ]
