# Generated by Django 4.1.1 on 2022-09-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_lizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LizerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Эквалайзер Категория')),
            ],
            options={
                'verbose_name': 'Эквалайзер - Категория',
                'verbose_name_plural': 'Эквалайзер - Категория',
            },
        ),
        migrations.AddField(
            model_name='lizer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.lizercategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
